%% Automatic MUSIC parameter search for every successful trial in one channel
% MATLAB R2024a; requires Signal Processing Toolbox.
%
% Input: one original-model fit MAT-file for one EEG channel.
% The script processes every successful Right and Left trial in
% FitAnalysis.finalResults.  For each trial it searches three MUSIC settings:
%   1) spectral-deconvolution regularization,
%   2) kernel-spectrum threshold, and
%   3) correlation order.
%
% It stops the per-trial MUSIC search at the first setting for which
% Root-MUSIC returns three finite, separated delays inside that trial's own
% fit window.  The three delayed components have equal, unnormalized unit
% coefficients [1, 1, 1].  Therefore no leading factor of 1/3 is used.
%
% Root-MUSIC estimates delay locations from the exponential phases in the
% deconvolved frequency-domain sequence.  A common nonzero amplitude factor
% would not change those phases or the ideal Root-MUSIC roots.  The script
% therefore reports the Root-MUSIC roots directly as Delta1Ms--Delta3Ms.
%
% This script does NOT draw a summed three-component time-domain response.
% Such a curve would require re-estimating the physical parameter vector
% theta after the three delays have been fixed.  Reusing and shifting the old
% single-response fit would not be a valid final three-component model.
%
% "Window-valid" is a numerical screening condition.  The PMUSIC support
% count and noise-stability summary should still be inspected before the
% numerical delays are interpreted physiologically.

clear;
clc;

%% USER SETTINGS
cfg = struct;
cfg.dataDir = fileparts(mfilename('fullpath'));

% TO RUN ANOTHER DATASET/CHANNEL, CHANGE ONLY THIS FILE NAME.
% Keep the exact name, including a suffix such as "(1)" when present.
cfg.fitFile = ...
    'DataA_Fz_single_trial_original_model_fit_fixed_ranges.mat';

% Fixed output folder.  DataA/DataB is read from the input filename, so
% results are saved under
% <input-file folder>/<outputFolder>/Data_A-or-Data_B/<channel>/.
% Re-running the same channel updates the files in this same location.
cfg.outputFolder = 'music_results';

% The script processes both conditions.  Change this to "Right" or "Left"
% only if a condition-specific run is wanted.
cfg.processDirections = ["Right", "Left"];

% Equal unit coefficients for the three delayed components:
% M(t) = sum_v S0(t-delta_v; theta) + xi(t).
% These coefficients specify the relative amplitudes as 1:1:1 without
% forcing them to sum to one.  No factor of 1/3 is introduced anywhere.
% The coefficients do not enter the Root-MUSIC delay calculation itself;
% they are stored in the output only to document the assumed model form.
cfg.numberOfComponents = 3;
cfg.componentWeights = ones(1, cfg.numberOfComponents);

% The main channel analysis uses the original observation without artificial
% noise.  Artificial noise is added only inside the stability experiment.
cfg.addWhiteNoise = false;
cfg.whiteNoiseStdFraction = 0;
cfg.whiteNoiseBaseSeed = 1729;

% Noise-stability experiment: 1%, 2%, and 5% of the trial-wise signal
% standard deviation, using 10 independent reproducible seeds per level.
cfg.runNoiseStability = true;
cfg.noiseStabilityLevels = [1e-2 2e-2 5e-2];
cfg.noiseStabilityReplicates = 10;
cfg.noiseStabilityBaseSeed = 271828;
cfg.noiseStabilityDelayToleranceMs = 7.8125; % two samples at 256 Hz

% Stage 1 uses the original preferred ranges.  Stage 2 is attempted only
% when Stage 1 finds no window-valid setting, and is explicitly marked as
% "extended" in the result tables.
cfg.searchStages(1).Name = "primary";
cfg.searchStages(1).RegularizationGrid = ...
    [1e-4 1e-5 1e-3 1e-6 1e-2 1e-7 1e-8];
cfg.searchStages(1).KernelThresholdGrid = ...
    [0.05 0.02 0.08 0.01 0.10 0.005];
cfg.searchStages(1).CorrelationOrderGrid = ...
    [6 8 5 7 9 10 12 14 16 18 20];

cfg.searchStages(2).Name = "extended";
cfg.searchStages(2).RegularizationGrid = ...
    [1e-10 1e-9 3e-9 3e-8 3e-7 3e-6 3e-5 3e-4 3e-3 3e-2 1e-1];
cfg.searchStages(2).KernelThresholdGrid = ...
    [0.001 0.002 0.003 0.0075 0.015 0.03 0.07 0.15 0.20];
cfg.searchStages(2).CorrelationOrderGrid = 4:24;
cfg.minimumFrequencyBins = 12;

% A candidate must remain inside the trial-specific fit window and the
% three delays must be separated by at least one 256-Hz sample.
cfg.edgeMarginMs = 0;
cfg.minimumDelaySeparationMs = 3.90625;
cfg.stopAtFirstWindowValid = true;

% PMUSIC is used for diagnostic confirmation, not for the stopping rule.
cfg.musicGridLength = 32768;
cfg.minimumPeakSeparationMs = 3.90625;
cfg.minimumPeakProminenceDb = 0;
cfg.maximumDisplayedPeaks = 12;
cfg.pmusicRootToleranceMs = 7.8125; % two samples at 256 Hz

cfg.verboseEveryAttempt = false;

%% Select and load one channel-level fit file
inputPath = fullfile(cfg.dataDir, cfg.fitFile);
if ~isfile(inputPath)
    error(['Input fit file was not found:\n  %s\n' ...
        'Change only cfg.fitFile in USER SETTINGS to the exact MAT-file name.'], ...
        inputPath);
end

loaded = load(inputPath, 'FitAnalysis');
if ~isfield(loaded, 'FitAnalysis')
    error('The selected MAT-file does not contain FitAnalysis.');
end
fitAnalysis = loaded.FitAnalysis;
if ~isfield(fitAnalysis, 'finalResults')
    error('FitAnalysis does not contain finalResults.');
end

datasetName = scalar_string(fitAnalysis.dataset);
if isfield(fitAnalysis, 'channel')
    channelName = scalar_string(fitAnalysis.channel);
else
    channelName = "unknown_channel";
end

parameterNames = string(fitAnalysis.model.parameter_names(:));
t1Index = find(strcmpi(parameterNames, 't1'), 1);
if isempty(t1Index)
    error('Parameter t1 was not found.');
end

allResults = fitAnalysis.finalResults;
nAll = numel(allResults);
directions = strings(nAll, 1);
trialNumbers = nan(nAll, 1);
successful = false(nAll, 1);
for q = 1:nAll
    directions(q) = scalar_string(allResults(q).direction);
    trialNumbers(q) = double(allResults(q).trial_number);
    successful(q) = logical(allResults(q).success);
end

% Process Right trials and then Left trials, each in trial-number order.
selectedIndices = [];
for requestedDirection = cfg.processDirections
    candidateIndices = find(successful & ...
        strcmpi(directions, requestedDirection));
    [~, chronologicalOrder] = sort(trialNumbers(candidateIndices));
    selectedIndices = [selectedIndices; ...
        candidateIndices(chronologicalOrder)]; %#ok<AGROW>
end
selectedIndices = unique(selectedIndices, 'stable');
if isempty(selectedIndices)
    error('No successful trials matched cfg.processDirections.');
end

fprintf('\nDataset: %s | Channel: %s\n', ...
    scalar_char(datasetName), scalar_char(channelName));
fprintf('Processing %d successful trials.\n', numel(selectedIndices));
fprintf(['Component coefficients: [%.6f %.6f %.6f]; main-run Gaussian ' ...
    'white-noise std = %.3g x trial signal std.\n'], ...
    cfg.componentWeights, cfg.whiteNoiseStdFraction);

%% Create a fixed output path
safeChannel = string(regexprep( ...
    channelName, '[^A-Za-z0-9_-]', '_'));

% Use the user-facing DataA/DataB prefix in the selected MAT filename for
% folder organization.  Do not use FitAnalysis.dataset here: older channel
% files may store an acquisition-session label (for example,
% "yu20150723a_Task-1") instead of "Data A" or "Data B".
[~, sourceFitStemForFolder] = fileparts(inputPath);
sourceFitStemForFolder = string(sourceFitStemForFolder);
if startsWith(sourceFitStemForFolder, "DataA_", ...
        'IgnoreCase', true)
    outputDatasetFolder = "Data_A";
elseif startsWith(sourceFitStemForFolder, "DataB_", ...
        'IgnoreCase', true)
    outputDatasetFolder = "Data_B";
else
    % Safe fallback for a future file that does not follow the DataA/DataB
    % filename convention.
    outputDatasetFolder = string(regexprep( ...
        datasetName, '[^A-Za-z0-9_-]', '_'));
    warning(['Could not determine DataA/DataB from the input filename. ' ...
        'Using FitAnalysis.dataset for the output folder instead.']);
end

outputDir = fullfile(fileparts(inputPath), ...
    cfg.outputFolder, outputDatasetFolder, safeChannel);
if ~exist(outputDir, 'dir')
    mkdir(outputDir);
end

summaryRows = repmat(empty_summary_row(), numel(selectedIndices), 1);

%% Process every trial independently
for trialPosition = 1:numel(selectedIndices)
    resultIndex = selectedIndices(trialPosition);
    result = allResults(resultIndex);
    direction = scalar_string(result.direction);
    trialNumber = double(result.trial_number);

    fprintf('\n[%d/%d] %s trial %g\n', ...
        trialPosition, numel(selectedIndices), ...
        scalar_char(direction), trialNumber);

    try
        summaryRow = search_one_trial( ...
            result, datasetName, channelName, ...
            t1Index, cfg);
    catch ME
        summaryRow = empty_summary_row();
        summaryRow.Dataset = datasetName;
        summaryRow.Channel = channelName;
        summaryRow.Direction = direction;
        summaryRow.TrialNumber = trialNumber;
        summaryRow.Status = "trial_error";
        summaryRow.Message = string(ME.message);
        fprintf('  ERROR: %s\n', ME.message);
    end

    summaryRows(trialPosition) = summaryRow;

    if summaryRow.WindowValid
        fprintf(['  FOUND after %d attempts: Root-MUSIC / final ' ...
            'delta = [%.3f, %.3f, %.3f] ms\n'], ...
            summaryRow.SearchAttempts, summaryRow.Delta1Ms, ...
            summaryRow.Delta2Ms, summaryRow.Delta3Ms);
        fprintf(['  stage = %s, reg = %.1e, threshold = %.3f, ' ...
            'order = %d, PMUSIC support = %d/3\n'], ...
            scalar_char(summaryRow.SearchStage), ...
            summaryRow.RegularizationFraction, ...
            summaryRow.KernelSpectrumThreshold, ...
            summaryRow.CorrelationOrder, ...
            summaryRow.PmusicPeaksNearRootCount);

    else
        fprintf('  No window-valid three-delay setting was found.\n');
        if summaryRow.BestNearMissInsideCount > 0
            fprintf(['  Best near miss: %d/3 inside, ' ...
                'delta = [%.3f, %.3f, %.3f] ms, ' ...
                'outside distance = %.3f ms\n'], ...
                summaryRow.BestNearMissInsideCount, ...
                summaryRow.BestNearMissDelta1Ms, ...
                summaryRow.BestNearMissDelta2Ms, ...
                summaryRow.BestNearMissDelta3Ms, ...
                summaryRow.BestNearMissOutsideDistanceMs);
            fprintf('  Best near-miss minimum separation = %.3f ms\n', ...
                summaryRow.BestNearMissMinimumSeparationMs);
        end
    end

end

%% Save the two essential channel-level tables
summaryTable = struct2table(summaryRows);
[~, sourceFitStem, sourceFitExtension] = fileparts(inputPath);
sourceFitFile = string([sourceFitStem sourceFitExtension]);
summaryTable.SourceFitFile = repmat( ...
    sourceFitFile, height(summaryTable), 1);
summaryCsvPath = fullfile(outputDir, ...
    "summary.csv");
stabilitySummaryCsvPath = fullfile(outputDir, ...
    "noise_stability_summary.csv");

writetable(summaryTable, summaryCsvPath);

noiseStabilitySummaryTable = struct2table( ...
    repmat(empty_stability_summary_row(), 0, 1));
if cfg.runNoiseStability
    fprintf('\nStarting noise-stability analysis: %d levels x %d replicates.\n', ...
        numel(cfg.noiseStabilityLevels), ...
        cfg.noiseStabilityReplicates);
    noiseStabilitySummaryTable = run_noise_stability( ...
        allResults, selectedIndices, datasetName, channelName, ...
        t1Index, cfg);
    writetable(noiseStabilitySummaryTable, ...
        stabilitySummaryCsvPath);
end

foundCount = nnz(summaryTable.WindowValid);
fprintf('\n========================================\n');
fprintf('Channel run completed: %d/%d trials had three window-valid delays.\n', ...
    foundCount, height(summaryTable));
fprintf('Delta summary:   %s\n', summaryCsvPath);
if cfg.runNoiseStability
    fprintf('Stability stats: %s\n', stabilitySummaryCsvPath);
end

displayColumns = {'Direction', 'TrialNumber', 'WindowValid', ...
    'Delta1Ms', 'Delta2Ms', 'Delta3Ms', ...
    'WhiteNoiseStd', ...
    'SearchStage', 'CorrelationOrder', ...
    'PmusicPeaksNearRootCount', 'Status'};
disp(summaryTable(:, displayColumns));

%% Search one trial
function summaryRow = search_one_trial( ...
        result, datasetName, channelName, t1Index, cfg)

    summaryRow = empty_summary_row();
    summaryRow.Dataset = datasetName;
    summaryRow.Channel = channelName;
    summaryRow.Direction = scalar_string(result.direction);
    summaryRow.TrialNumber = double(result.trial_number);
    summaryRow.OriginalNcoup = double(result.N_coup);
    summaryRow.OriginalR2 = double(result.metrics.R2);
    summaryRow.Weight1 = cfg.componentWeights(1);
    summaryRow.Weight2 = cfg.componentWeights(2);
    summaryRow.Weight3 = cfg.componentWeights(3);

    t = double(result.t_data(:));
    observedOriginal = double(result.y_data(:));
    fitted = double(result.y_model(:));
    parameters = double(result.parameters(:));
    t1 = parameters(t1Index);
    dt = median(diff(t));
    Fs = 1/dt;
    fitStartMs = 1000*t(1) + cfg.edgeMarginMs;
    fitEndMs = 1000*t(end) - cfg.edgeMarginMs;
    if fitStartMs >= fitEndMs
        error('edgeMarginMs removes the complete trial fit window.');
    end

    summaryRow.OriginalT1Ms = 1000*t1;
    summaryRow.FitStartMs = fitStartMs;
    summaryRow.FitEndMs = fitEndMs;
    summaryRow.FsHz = Fs;

    [observed, whiteNoiseStd, whiteNoiseSeed] = ...
        add_small_white_noise(observedOriginal, ...
        summaryRow.Direction, summaryRow.TrialNumber, cfg);
    summaryRow.WhiteNoiseEnabled = ...
        cfg.addWhiteNoise && cfg.whiteNoiseStdFraction > 0;
    summaryRow.WhiteNoiseStdFraction = cfg.whiteNoiseStdFraction;
    summaryRow.WhiteNoiseStd = whiteNoiseStd;
    summaryRow.WhiteNoiseSeed = whiteNoiseSeed;

    % Build the transition-centered, trial-specific fitted kernel S0.
    N = numel(t);
    transformLength = 2^nextpow2(4*N);
    observedBuffer = zeros(transformLength, 1);
    observedBuffer(1:N) = observed;

    localTimeOriginal = t - t1;
    if min(localTimeOriginal) >= 0 || max(localTimeOriginal) <= 0
        error('The fitted t1 is outside this trial fit window.');
    end

    positiveCount = floor(max(localTimeOriginal)/dt) + 1;
    negativeCount = floor(-min(localTimeOriginal)/dt);
    localTimePositive = (0:positiveCount-1).' * dt;
    localTimeNegative = -(1:negativeCount).' * dt;
    postTransition = interp1(localTimeOriginal, fitted, ...
        localTimePositive, 'pchip');
    preTransition = interp1(localTimeOriginal, fitted, ...
        localTimeNegative, 'pchip');

    kernelBuffer = zeros(transformLength, 1);
    kernelBuffer(1:numel(postTransition)) = postTransition;
    if ~isempty(preTransition)
        kernelBuffer(end-numel(preTransition)+1:end) = ...
            flipud(preTransition);
    end

    observedSpectrum = fft(observedBuffer);
    kernelSpectrum = fft(kernelBuffer);
    positiveIndices = (2:(floor(transformLength/2)+1)).';
    relativeKernelMagnitude = abs(kernelSpectrum(positiveIndices));
    relativeKernelMagnitude = relativeKernelMagnitude ./ ...
        max(relativeKernelMagnitude);

    attemptCount = 0;
    winner = [];
    bestNearMiss = [];

    for stageIndex = 1:numel(cfg.searchStages)
        stage = cfg.searchStages(stageIndex);

        for regularizationFraction = stage.RegularizationGrid
            lambda = regularizationFraction * ...
                max(abs(kernelSpectrum).^2);
            % With unit coefficients, the ideal deconvolved sequence is
            %   M~/S0~ = sum_v exp(-j*omega*delta_v) + noise/S0~.
            % Root-MUSIC uses the phase progression of these exponentials to
            % estimate the delays.  No normalization by the component count
            % and no leading factor of 1/3 are applied here.
            deconvolved = observedSpectrum .* conj(kernelSpectrum) ./ ...
                (abs(kernelSpectrum).^2 + lambda);

            for kernelThreshold = stage.KernelThresholdGrid
                supported = relativeKernelMagnitude >= kernelThreshold;
                [runStart, runEnd] = longest_true_run(supported);

                if isempty(runStart) || ...
                        (runEnd-runStart+1) < cfg.minimumFrequencyBins
                    for correlationOrder = stage.CorrelationOrderGrid
                        attemptCount = attemptCount + 1;
                        row = base_attempt_row( ...
                            datasetName, channelName, result, ...
                            attemptCount, stage.Name, ...
                            regularizationFraction, ...
                            kernelThreshold, correlationOrder);
                        row.Status = "insufficient_frequency_bins";
                    end
                    continue;
                end

                selectedIndices = positiveIndices(runStart:runEnd);
                deconvolvedSequence = conj(deconvolved(selectedIndices));

                for correlationOrder = stage.CorrelationOrderGrid
                    attemptCount = attemptCount + 1;
                    row = base_attempt_row( ...
                        datasetName, channelName, result, ...
                        attemptCount, stage.Name, ...
                        regularizationFraction, ...
                        kernelThreshold, correlationOrder);
                    row.DFTStartBin = selectedIndices(1)-1;
                    row.DFTEndBin = selectedIndices(end)-1;
                    row.NumberOfDFTBins = numel(selectedIndices);

                    if correlationOrder <= cfg.numberOfComponents || ...
                            correlationOrder >= ...
                            numel(deconvolvedSequence)- ...
                            cfg.numberOfComponents
                        row.Status = "invalid_correlation_order";
                        continue;
                    end

                    try
                        [~, correlationMatrix] = corrmtx( ...
                            deconvolvedSequence, ...
                            correlationOrder, 'modified');
                        correlationMatrix = ...
                            (correlationMatrix + correlationMatrix')/2;
                        minimumEigenvalue = ...
                            min(real(eig(correlationMatrix)));
                        if minimumEigenvalue < 0
                            correlationMatrix = correlationMatrix + ...
                                (-minimumEigenvalue + ...
                                eps(norm(correlationMatrix, 2))) * ...
                                eye(size(correlationMatrix));
                        end

                        [rootFrequency, rootPower] = rootmusic( ...
                            correlationMatrix, ...
                            cfg.numberOfComponents, 'corr');
                        rootFrequency = mod(real(rootFrequency(:)), 2*pi);
                        rootPower = real(rootPower(:));
                        if numel(rootFrequency) < ...
                                cfg.numberOfComponents
                            error(['Root-MUSIC returned fewer ' ...
                                'than three roots.']);
                        end

                        rootDelaySeconds = t(1) + ...
                            rootFrequency * ...
                            transformLength/(2*pi) * dt;
                        rootDelayMs = 1000*rootDelaySeconds;
                        [rootDelayMs, chronologicalOrder] = ...
                            sort(rootDelayMs);
                        rootPower = rootPower(chronologicalOrder);
                        insideWindow = isfinite(rootDelayMs) & ...
                            rootDelayMs >= fitStartMs & ...
                            rootDelayMs <= fitEndMs;
                        delaySeparation = diff(rootDelayMs);
                        separated = all(delaySeparation >= ...
                            cfg.minimumDelaySeparationMs);

                        belowDistance = ...
                            max(fitStartMs-rootDelayMs, 0);
                        aboveDistance = ...
                            max(rootDelayMs-fitEndMs, 0);
                        outsideDistance = ...
                            sum(belowDistance+aboveDistance);

                        row.Delta1Ms = rootDelayMs(1);
                        row.Delta2Ms = rootDelayMs(2);
                        row.Delta3Ms = rootDelayMs(3);
                        row.Power1 = rootPower(1);
                        row.Power2 = rootPower(2);
                        row.Power3 = rootPower(3);
                        row.NumberInsideFitWindow = nnz(insideWindow);
                        row.OutsideWindowDistanceMs = outsideDistance;
                        row.AllInsideFitWindow = all(insideWindow);
                        row.MinimumSeparationMs = min(delaySeparation);
                        row.WindowValid = ...
                            row.AllInsideFitWindow && separated;
                        row.Status = "ok";
                    catch ME
                        row.Status = "failed";
                        row.Message = string(ME.message);
                    end

                    if row.Status == "ok"
                        if isempty(bestNearMiss) || ...
                                row.NumberInsideFitWindow > ...
                                bestNearMiss.NumberInsideFitWindow || ...
                                (row.NumberInsideFitWindow == ...
                                bestNearMiss.NumberInsideFitWindow && ...
                                row.OutsideWindowDistanceMs < ...
                                bestNearMiss.OutsideWindowDistanceMs)
                            bestNearMiss = row;
                        end
                    end

                    if cfg.verboseEveryAttempt
                        fprintf(['    %4d %s reg=%-8.1e ' ...
                            'thr=%-6.3f order=%2d ' ...
                            'delta=[%8.2f %8.2f %8.2f] ' ...
                            'inside=%d\n'], ...
                            row.SearchIndex, scalar_char(row.SearchStage), ...
                            row.RegularizationFraction, ...
                            row.KernelSpectrumThreshold, ...
                            row.CorrelationOrder, row.Delta1Ms, ...
                            row.Delta2Ms, row.Delta3Ms, ...
                            row.WindowValid);
                    end

                    if row.WindowValid
                        winner = struct( ...
                            'row', row, ...
                            'selectedIndices', selectedIndices, ...
                            'deconvolvedSequence', deconvolvedSequence);
                        if cfg.stopAtFirstWindowValid
                            break;
                        end
                    end
                end

                if ~isempty(winner) && cfg.stopAtFirstWindowValid
                    break;
                end
            end

            if ~isempty(winner) && cfg.stopAtFirstWindowValid
                break;
            end
        end

        if ~isempty(winner) && cfg.stopAtFirstWindowValid
            break;
        end
    end

    summaryRow.SearchAttempts = attemptCount;

    if isempty(winner)
        if ~isempty(bestNearMiss)
            summaryRow.BestNearMissInsideCount = ...
                bestNearMiss.NumberInsideFitWindow;
            summaryRow.BestNearMissOutsideDistanceMs = ...
                bestNearMiss.OutsideWindowDistanceMs;
            summaryRow.BestNearMissDelta1Ms = bestNearMiss.Delta1Ms;
            summaryRow.BestNearMissDelta2Ms = bestNearMiss.Delta2Ms;
            summaryRow.BestNearMissDelta3Ms = bestNearMiss.Delta3Ms;
            summaryRow.BestNearMissMinimumSeparationMs = ...
                bestNearMiss.MinimumSeparationMs;
            summaryRow.BestNearMissSearchStage = ...
                bestNearMiss.SearchStage;
            summaryRow.BestNearMissRegularizationFraction = ...
                bestNearMiss.RegularizationFraction;
            summaryRow.BestNearMissKernelSpectrumThreshold = ...
                bestNearMiss.KernelSpectrumThreshold;
            summaryRow.BestNearMissCorrelationOrder = ...
                bestNearMiss.CorrelationOrder;
        end
        summaryRow.Status = "no_window_valid_setting";
        return;
    end

    % Compute PMUSIC only for the accepted setting.
    winningRow = winner.row;
    [dataMatrix, ~] = corrmtx(winner.deconvolvedSequence, ...
        winningRow.CorrelationOrder, 'modified');
    [pseudospectrum, normalizedAngularFrequency] = pmusic( ...
        dataMatrix, cfg.numberOfComponents, ...
        cfg.musicGridLength, 'whole');
    pseudospectrum = abs(pseudospectrum(:));
    normalizedAngularFrequency = normalizedAngularFrequency(:);
    delaySamples = normalizedAngularFrequency * ...
        transformLength/(2*pi);
    absoluteDelaySeconds = t(1) + delaySamples*dt;
    validDelay = absoluteDelaySeconds >= t(1) & ...
        absoluteDelaySeconds <= t(end);
    delayMsGrid = 1000*absoluteDelaySeconds(validDelay);
    pseudospectrum = pseudospectrum(validDelay);
    pseudospectrumDb = ...
        10*log10(pseudospectrum/max(pseudospectrum));

    [~, peakLocationsMs] = ...
        findpeaks(pseudospectrumDb, delayMsGrid, ...
        'MinPeakDistance', cfg.minimumPeakSeparationMs, ...
        'MinPeakProminence', cfg.minimumPeakProminenceDb, ...
        'SortStr', 'descend', ...
        'NPeaks', cfg.maximumDisplayedPeaks);
    peakLocationsMs = sort(peakLocationsMs);

    rootMusicDelays = [winningRow.Delta1Ms, ...
        winningRow.Delta2Ms, winningRow.Delta3Ms];
    nearRootCount = ...
        distinct_peak_support(rootMusicDelays, peakLocationsMs, ...
        cfg.pmusicRootToleranceMs);

    % The Root-MUSIC roots are the final delay estimates from this stage.
    % No time-domain three-component curve is constructed here.  In
    % particular, the old fitted response is not shifted and summed because
    % theta must first be re-estimated conditionally on these three delays.

    summaryRow.WindowValid = true;
    summaryRow.SettingSelected = true;
    summaryRow.SearchStage = winningRow.SearchStage;
    summaryRow.RegularizationFraction = ...
        winningRow.RegularizationFraction;
    summaryRow.KernelSpectrumThreshold = ...
        winningRow.KernelSpectrumThreshold;
    summaryRow.CorrelationOrder = winningRow.CorrelationOrder;
    summaryRow.DFTStartBin = winningRow.DFTStartBin;
    summaryRow.DFTEndBin = winningRow.DFTEndBin;
    summaryRow.NumberOfDFTBins = winningRow.NumberOfDFTBins;
    summaryRow.Delta1Ms = rootMusicDelays(1);
    summaryRow.Delta2Ms = rootMusicDelays(2);
    summaryRow.Delta3Ms = rootMusicDelays(3);
    summaryRow.MinimumSeparationMs = min(diff(rootMusicDelays));
    summaryRow.PmusicLocalPeakCount = numel(peakLocationsMs);
    summaryRow.PmusicPeaksNearRootCount = nearRootCount;
    summaryRow.Status = "window_valid_unit_weight_root_delays_check_pmusic";

end

%% Helpers
function [bestCount, matchedDistances, matchedPeakIndices] = ...
        distinct_peak_support(rootDelays, peakLocations, toleranceMs)
    % One PMUSIC maximum may support at most one Root-MUSIC candidate.
    rootDelays = double(rootDelays(:)).';
    peakLocations = double(peakLocations(:)).';
    bestCount = 0;
    bestTotalDistance = inf;
    matchedDistances = nan(1, 3);
    matchedPeakIndices = zeros(1, 3);
    choices = 0:numel(peakLocations);
    for peak1 = choices
        for peak2 = choices
            for peak3 = choices
                assignment = [peak1 peak2 peak3];
                used = assignment(assignment > 0);
                if numel(unique(used)) ~= numel(used)
                    continue;
                end

                distances = nan(1, 3);
                admissible = true;
                for rootIndex = 1:3
                    peakIndex = assignment(rootIndex);
                    if peakIndex == 0
                        continue;
                    end
                    distance = abs(rootDelays(rootIndex)- ...
                        peakLocations(peakIndex));
                    if ~isfinite(rootDelays(rootIndex)) || ...
                            distance > toleranceMs
                        admissible = false;
                        break;
                    end
                    distances(rootIndex) = distance;
                end
                if ~admissible
                    continue;
                end

                matched = assignment > 0;
                count = nnz(matched);
                totalDistance = sum(distances(matched));
                if count > bestCount || ...
                        (count == bestCount && ...
                        totalDistance < bestTotalDistance)
                    bestCount = count;
                    bestTotalDistance = totalDistance;
                    matchedDistances = distances;
                    matchedPeakIndices = assignment;
                end
            end
        end
    end
end

function [observedNoisy, noiseStd, trialSeed] = ...
        add_small_white_noise(observedOriginal, direction, ...
        trialNumber, cfg)

    observedOriginal = double(observedOriginal(:));

    observedNoisy = observedOriginal;
    noiseStd = 0;
    trialSeed = NaN;
    if ~cfg.addWhiteNoise || cfg.whiteNoiseStdFraction == 0
        return;
    end

    noiseStd = cfg.whiteNoiseStdFraction * std(observedOriginal);
    if noiseStd == 0
        return;
    end

    directionOffset = 200000;
    if strcmpi(scalar_string(direction), "Right")
        directionOffset = 0;
    elseif strcmpi(scalar_string(direction), "Left")
        directionOffset = 100000;
    end
    maximumSeed = double(intmax('uint32'));
    trialSeed = mod(round(double(cfg.whiteNoiseBaseSeed)) + ...
        directionOffset + round(double(trialNumber)), maximumSeed);

    stream = RandStream('mt19937ar', 'Seed', trialSeed);
    observedNoisy = observedOriginal + ...
        noiseStd * randn(stream, size(observedOriginal));
end

function stabilitySummaryTable = run_noise_stability( ...
        allResults, selectedIndices, datasetName, channelName, ...
        t1Index, cfg)

    noiseLevels = double(cfg.noiseStabilityLevels(:)).';
    replicateCount = double(cfg.noiseStabilityReplicates);
    maximumSummaryRows = numel(selectedIndices) * ...
        numel(noiseLevels);
    stabilitySummaryRows = repmat( ...
        empty_stability_summary_row(), maximumSummaryRows, 1);
    summaryRowCount = 0;

    for trialPosition = 1:numel(selectedIndices)
        result = allResults(selectedIndices(trialPosition));
        direction = scalar_string(result.direction);
        trialNumber = double(result.trial_number);
        fprintf('\n  Stability [%d/%d] %s trial %g\n', ...
            trialPosition, numel(selectedIndices), ...
            scalar_char(direction), trialNumber);

        baselineCfg = cfg;
        baselineCfg.addWhiteNoise = false;
        baselineCfg.whiteNoiseStdFraction = 0;
        baselineCfg.verboseEveryAttempt = false;
        baselineSummary = safe_stability_search( ...
            result, datasetName, channelName, t1Index, baselineCfg);

        for levelIndex = 1:numel(noiseLevels)
            noiseLevel = noiseLevels(levelIndex);
            levelRows = repmat(empty_stability_run_row(), ...
                replicateCount, 1);

            for replicateIndex = 1:replicateCount
                searchWasExecuted = true;
                stabilityCfg = cfg;
                stabilityCfg.addWhiteNoise = true;
                stabilityCfg.whiteNoiseStdFraction = noiseLevel;
                stabilityCfg.whiteNoiseBaseSeed = ...
                    stability_seed_base(cfg, levelIndex, ...
                    replicateIndex);
                stabilityCfg.verboseEveryAttempt = false;
                replicateSummary = safe_stability_search( ...
                    result, datasetName, channelName, ...
                    t1Index, stabilityCfg);

                stabilityRunRow = stability_run_from_summary( ...
                    replicateSummary, baselineSummary, noiseLevel, ...
                    replicateIndex, searchWasExecuted, cfg);
                levelRows(replicateIndex) = stabilityRunRow;
            end

            summaryRowCount = summaryRowCount+1;
            stabilitySummaryRows(summaryRowCount) = ...
                summarize_stability_level(levelRows, cfg);

            fprintf(['    noise=%5.2f%%: window-valid %.2f, ' ...
                'delay-stable %.2f, parameter-change %.2f\n'], ...
                100*noiseLevel, ...
                stabilitySummaryRows(summaryRowCount).WindowValidProportion, ...
                stabilitySummaryRows(summaryRowCount). ...
                    DelayStableProportionAmongWindowValid, ...
                stabilitySummaryRows(summaryRowCount). ...
                    SearchParameterChangeProportion);
        end

    end

    stabilitySummaryTable = struct2table( ...
        stabilitySummaryRows(1:summaryRowCount));
end

function summaryRow = safe_stability_search( ...
        result, datasetName, channelName, t1Index, cfg)
    try
        summaryRow = search_one_trial( ...
            result, datasetName, channelName, t1Index, cfg);
    catch ME
        summaryRow = empty_summary_row();
        summaryRow.Dataset = datasetName;
        summaryRow.Channel = channelName;
        summaryRow.Direction = scalar_string(result.direction);
        summaryRow.TrialNumber = double(result.trial_number);
        summaryRow.Weight1 = cfg.componentWeights(1);
        summaryRow.Weight2 = cfg.componentWeights(2);
        summaryRow.Weight3 = cfg.componentWeights(3);
        summaryRow.WhiteNoiseStdFraction = ...
            cfg.whiteNoiseStdFraction;
        summaryRow.Status = "stability_run_error";
        summaryRow.Message = string(ME.message);
    end
end

function seedBase = stability_seed_base( ...
        cfg, levelIndex, replicateIndex)
    maximumSeed = double(intmax('uint32'));
    seedBase = mod(round(double(cfg.noiseStabilityBaseSeed)) + ...
        1000000*double(levelIndex) + ...
        10000*double(replicateIndex), maximumSeed);
end

function row = stability_run_from_summary( ...
        resultSummary, baselineSummary, noiseLevel, ...
        replicateIndex, searchWasExecuted, cfg)

    row = empty_stability_run_row();
    row.Dataset = resultSummary.Dataset;
    row.Channel = resultSummary.Channel;
    row.Direction = resultSummary.Direction;
    row.TrialNumber = resultSummary.TrialNumber;
    row.NoiseLevelFraction = noiseLevel;
    row.NoiseLevelPercent = 100*noiseLevel;
    row.Replicate = replicateIndex;
    row.SearchWasExecuted = searchWasExecuted;
    row.WhiteNoiseStd = resultSummary.WhiteNoiseStd;
    row.WhiteNoiseSeed = resultSummary.WhiteNoiseSeed;
    row.SearchAttempts = resultSummary.SearchAttempts;
    row.WindowValid = resultSummary.WindowValid;
    row.AllThreeRootsInsideWindow = ...
        resultSummary.WindowValid || ...
        resultSummary.BestNearMissInsideCount == 3;
    row.SearchStage = resultSummary.SearchStage;
    row.RegularizationFraction = ...
        resultSummary.RegularizationFraction;
    row.KernelSpectrumThreshold = ...
        resultSummary.KernelSpectrumThreshold;
    row.CorrelationOrder = resultSummary.CorrelationOrder;
    row.DFTStartBin = resultSummary.DFTStartBin;
    row.DFTEndBin = resultSummary.DFTEndBin;
    row.NumberOfDFTBins = resultSummary.NumberOfDFTBins;
    row.Delta1Ms = resultSummary.Delta1Ms;
    row.Delta2Ms = resultSummary.Delta2Ms;
    row.Delta3Ms = resultSummary.Delta3Ms;
    row.PmusicPeaksNearRootCount = ...
        resultSummary.PmusicPeaksNearRootCount;
    row.Status = resultSummary.Status;
    row.Message = resultSummary.Message;

    row.SearchParametersComparable = ...
        baselineSummary.WindowValid && resultSummary.WindowValid;
    if row.SearchParametersComparable
        row.SearchParametersChanged = ...
            selected_settings_changed( ...
            resultSummary, baselineSummary);
        baselineDelays = [baselineSummary.Delta1Ms, ...
            baselineSummary.Delta2Ms, baselineSummary.Delta3Ms];
        currentDelays = [resultSummary.Delta1Ms, ...
            resultSummary.Delta2Ms, resultSummary.Delta3Ms];
        row.DelaysWithinToleranceOfBaseline = ...
            all(abs(currentDelays-baselineDelays) <= ...
            cfg.noiseStabilityDelayToleranceMs);
    end
end

function changed = selected_settings_changed( ...
        resultSummary, baselineSummary)
    resultNumbers = [ ...
        resultSummary.RegularizationFraction, ...
        resultSummary.KernelSpectrumThreshold, ...
        resultSummary.CorrelationOrder, ...
        resultSummary.DFTStartBin, ...
        resultSummary.DFTEndBin, ...
        resultSummary.NumberOfDFTBins];
    baselineNumbers = [ ...
        baselineSummary.RegularizationFraction, ...
        baselineSummary.KernelSpectrumThreshold, ...
        baselineSummary.CorrelationOrder, ...
        baselineSummary.DFTStartBin, ...
        baselineSummary.DFTEndBin, ...
        baselineSummary.NumberOfDFTBins];
    sameNumbers = all((resultNumbers == baselineNumbers) | ...
        (isnan(resultNumbers) & isnan(baselineNumbers)));
    sameStage = strcmpi(resultSummary.SearchStage, ...
        baselineSummary.SearchStage);
    changed = ~(sameNumbers && sameStage);
end

function row = summarize_stability_level(levelRows, cfg)
    row = empty_stability_summary_row();
    row.Dataset = levelRows(1).Dataset;
    row.Channel = levelRows(1).Channel;
    row.Direction = levelRows(1).Direction;
    row.TrialNumber = levelRows(1).TrialNumber;
    row.NoiseLevelFraction = levelRows(1).NoiseLevelFraction;
    row.NoiseLevelPercent = levelRows(1).NoiseLevelPercent;
    row.ReplicateCount = numel(levelRows);
    row.DelayToleranceMs = cfg.noiseStabilityDelayToleranceMs;

    windowValid = [levelRows.WindowValid];
    allInside = [levelRows.AllThreeRootsInsideWindow];
    row.WindowValidCount = nnz(windowValid);
    row.WindowValidProportion = mean(double(windowValid));
    row.AllThreeRootsInsideWindowCount = nnz(allInside);
    row.AllThreeRootsInsideWindowProportion = ...
        mean(double(allInside));
    row.MeanSearchAttempts = mean([levelRows.SearchAttempts]);

    % Root-MUSIC roots are the final delay estimates from this stage.
    row.PmusicSupportDelayType = "root_music_final";
    supportCounts = [levelRows.PmusicPeaksNearRootCount];
    row.Pmusic0of3Count = nnz(supportCounts == 0);
    row.Pmusic1of3Count = nnz(supportCounts == 1);
    row.Pmusic2of3Count = nnz(supportCounts == 2);
    row.Pmusic3of3Count = nnz(supportCounts == 3);
    row.Pmusic0of3Proportion = ...
        row.Pmusic0of3Count/row.ReplicateCount;
    row.Pmusic1of3Proportion = ...
        row.Pmusic1of3Count/row.ReplicateCount;
    row.Pmusic2of3Proportion = ...
        row.Pmusic2of3Count/row.ReplicateCount;
    row.Pmusic3of3Proportion = ...
        row.Pmusic3of3Count/row.ReplicateCount;
    if row.WindowValidCount > 0
        row.DelayStableProportionAmongWindowValid = ...
            nnz([levelRows.DelaysWithinToleranceOfBaseline] & ...
            windowValid)/row.WindowValidCount;
    end

    comparableSettings = [levelRows.SearchParametersComparable];
    row.SearchParameterComparableCount = nnz(comparableSettings);
    if row.SearchParameterComparableCount > 0
        changedSettings = [levelRows.SearchParametersChanged];
        row.SearchParameterChangedCount = ...
            nnz(changedSettings(comparableSettings));
        row.SearchParameterChangeProportion = ...
            row.SearchParameterChangedCount / ...
            row.SearchParameterComparableCount;
    end

    [row.Delta1MeanMs, row.Delta1MedianMs, ...
        row.Delta1StdMs, row.Delta1CI95LowMs, ...
        row.Delta1CI95HighMs] = finite_delay_statistics( ...
        [levelRows(windowValid).Delta1Ms]);
    [row.Delta2MeanMs, row.Delta2MedianMs, ...
        row.Delta2StdMs, row.Delta2CI95LowMs, ...
        row.Delta2CI95HighMs] = finite_delay_statistics( ...
        [levelRows(windowValid).Delta2Ms]);
    [row.Delta3MeanMs, row.Delta3MedianMs, ...
        row.Delta3StdMs, row.Delta3CI95LowMs, ...
        row.Delta3CI95HighMs] = finite_delay_statistics( ...
        [levelRows(windowValid).Delta3Ms]);
end

function [meanValue, medianValue, stdValue, ciLow, ciHigh] = ...
        finite_delay_statistics(values)
    values = double(values(:));
    values = values(isfinite(values));
    if isempty(values)
        meanValue = NaN;
        medianValue = NaN;
        stdValue = NaN;
        ciLow = NaN;
        ciHigh = NaN;
        return;
    end
    meanValue = mean(values);
    medianValue = median(values);
    stdValue = std(values);
    ciLow = linear_percentile(values, 0.025);
    ciHigh = linear_percentile(values, 0.975);
end

function percentileValue = linear_percentile(values, probability)
    values = sort(double(values(:)));
    if numel(values) == 1
        percentileValue = values(1);
        return;
    end
    position = 1+(numel(values)-1)*double(probability);
    lowerIndex = floor(position);
    upperIndex = ceil(position);
    fraction = position-lowerIndex;
    percentileValue = values(lowerIndex) + ...
        fraction*(values(upperIndex)-values(lowerIndex));
end

function row = base_attempt_row(datasetName, channelName, result, ...
        searchIndex, searchStage, regularizationFraction, ...
        kernelThreshold, correlationOrder)
    row = empty_attempt_row();
    row.Dataset = datasetName;
    row.Channel = channelName;
    row.Direction = scalar_string(result.direction);
    row.TrialNumber = double(result.trial_number);
    row.SearchIndex = searchIndex;
    row.SearchStage = searchStage;
    row.RegularizationFraction = regularizationFraction;
    row.KernelSpectrumThreshold = kernelThreshold;
    row.CorrelationOrder = correlationOrder;
end

function [runStart, runEnd] = longest_true_run(mask)
    mask = logical(mask(:));
    edges = diff([false; mask; false]);
    starts = find(edges == 1);
    ends = find(edges == -1)-1;
    if isempty(starts)
        runStart = [];
        runEnd = [];
        return;
    end
    [~, best] = max(ends-starts+1);
    runStart = starts(best);
    runEnd = ends(best);
end

function value = scalar_string(value)
    while iscell(value) && isscalar(value)
        value = value{1};
    end
    value = string(value);
    value = value(1);
end

function value = scalar_char(value)
    value = char(scalar_string(value));
end

function row = empty_summary_row()
    row = struct( ...
        'Dataset', "", ...
        'Channel', "", ...
        'Direction', "", ...
        'TrialNumber', NaN, ...
        'OriginalT1Ms', NaN, ...
        'OriginalNcoup', NaN, ...
        'OriginalR2', NaN, ...
        'FsHz', NaN, ...
        'FitStartMs', NaN, ...
        'FitEndMs', NaN, ...
        'WhiteNoiseEnabled', false, ...
        'WhiteNoiseStdFraction', NaN, ...
        'WhiteNoiseStd', NaN, ...
        'WhiteNoiseSeed', NaN, ...
        'Weight1', NaN, ...
        'Weight2', NaN, ...
        'Weight3', NaN, ...
        'SearchAttempts', 0, ...
        'SettingSelected', false, ...
        'WindowValid', false, ...
        'SearchStage', "", ...
        'RegularizationFraction', NaN, ...
        'KernelSpectrumThreshold', NaN, ...
        'CorrelationOrder', NaN, ...
        'DFTStartBin', NaN, ...
        'DFTEndBin', NaN, ...
        'NumberOfDFTBins', NaN, ...
        'Delta1Ms', NaN, ...
        'Delta2Ms', NaN, ...
        'Delta3Ms', NaN, ...
        'MinimumSeparationMs', NaN, ...
        'PmusicLocalPeakCount', 0, ...
        'PmusicPeaksNearRootCount', 0, ...
        'BestNearMissInsideCount', 0, ...
        'BestNearMissOutsideDistanceMs', NaN, ...
        'BestNearMissDelta1Ms', NaN, ...
        'BestNearMissDelta2Ms', NaN, ...
        'BestNearMissDelta3Ms', NaN, ...
        'BestNearMissMinimumSeparationMs', NaN, ...
        'BestNearMissSearchStage', "", ...
        'BestNearMissRegularizationFraction', NaN, ...
        'BestNearMissKernelSpectrumThreshold', NaN, ...
        'BestNearMissCorrelationOrder', NaN, ...
        'Status', "", ...
        'Message', "");
end

function row = empty_attempt_row()
    row = struct( ...
        'Dataset', "", ...
        'Channel', "", ...
        'Direction', "", ...
        'TrialNumber', NaN, ...
        'SearchIndex', NaN, ...
        'SearchStage', "", ...
        'RegularizationFraction', NaN, ...
        'KernelSpectrumThreshold', NaN, ...
        'CorrelationOrder', NaN, ...
        'DFTStartBin', NaN, ...
        'DFTEndBin', NaN, ...
        'NumberOfDFTBins', NaN, ...
        'Delta1Ms', NaN, ...
        'Delta2Ms', NaN, ...
        'Delta3Ms', NaN, ...
        'Power1', NaN, ...
        'Power2', NaN, ...
        'Power3', NaN, ...
        'NumberInsideFitWindow', 0, ...
        'OutsideWindowDistanceMs', NaN, ...
        'AllInsideFitWindow', false, ...
        'MinimumSeparationMs', NaN, ...
        'WindowValid', false, ...
        'Status', "", ...
        'Message', "");
end

function row = empty_stability_run_row()
    row = struct( ...
        'Dataset', "", ...
        'Channel', "", ...
        'Direction', "", ...
        'TrialNumber', NaN, ...
        'NoiseLevelFraction', NaN, ...
        'NoiseLevelPercent', NaN, ...
        'Replicate', NaN, ...
        'SearchWasExecuted', false, ...
        'WhiteNoiseStd', NaN, ...
        'WhiteNoiseSeed', NaN, ...
        'SearchAttempts', 0, ...
        'WindowValid', false, ...
        'AllThreeRootsInsideWindow', false, ...
        'SearchStage', "", ...
        'RegularizationFraction', NaN, ...
        'KernelSpectrumThreshold', NaN, ...
        'CorrelationOrder', NaN, ...
        'DFTStartBin', NaN, ...
        'DFTEndBin', NaN, ...
        'NumberOfDFTBins', NaN, ...
        'Delta1Ms', NaN, ...
        'Delta2Ms', NaN, ...
        'Delta3Ms', NaN, ...
        'PmusicPeaksNearRootCount', 0, ...
        'SearchParametersComparable', false, ...
        'SearchParametersChanged', NaN, ...
        'DelaysWithinToleranceOfBaseline', false, ...
        'Status', "", ...
        'Message', "");
end

function row = empty_stability_summary_row()
    row = struct( ...
        'Dataset', "", ...
        'Channel', "", ...
        'Direction', "", ...
        'TrialNumber', NaN, ...
        'NoiseLevelFraction', NaN, ...
        'NoiseLevelPercent', NaN, ...
        'ReplicateCount', 0, ...
        'DelayToleranceMs', NaN, ...
        'WindowValidCount', 0, ...
        'WindowValidProportion', NaN, ...
        'AllThreeRootsInsideWindowCount', 0, ...
        'AllThreeRootsInsideWindowProportion', NaN, ...
        'MeanSearchAttempts', NaN, ...
        'PmusicSupportDelayType', "", ...
        'Pmusic0of3Count', 0, ...
        'Pmusic1of3Count', 0, ...
        'Pmusic2of3Count', 0, ...
        'Pmusic3of3Count', 0, ...
        'Pmusic0of3Proportion', NaN, ...
        'Pmusic1of3Proportion', NaN, ...
        'Pmusic2of3Proportion', NaN, ...
        'Pmusic3of3Proportion', NaN, ...
        'SearchParameterComparableCount', 0, ...
        'SearchParameterChangedCount', 0, ...
        'SearchParameterChangeProportion', NaN, ...
        'DelayStableProportionAmongWindowValid', NaN, ...
        'Delta1MeanMs', NaN, ...
        'Delta1MedianMs', NaN, ...
        'Delta1StdMs', NaN, ...
        'Delta1CI95LowMs', NaN, ...
        'Delta1CI95HighMs', NaN, ...
        'Delta2MeanMs', NaN, ...
        'Delta2MedianMs', NaN, ...
        'Delta2StdMs', NaN, ...
        'Delta2CI95LowMs', NaN, ...
        'Delta2CI95HighMs', NaN, ...
        'Delta3MeanMs', NaN, ...
        'Delta3MedianMs', NaN, ...
        'Delta3StdMs', NaN, ...
        'Delta3CI95LowMs', NaN, ...
        'Delta3CI95HighMs', NaN);
end
